{% set name = "pdfstream" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d1f20f355353fa841653d631fd7a8b51a8ea4dfe68910bf56393ae34b9c31232

build:
  number: 0
  noarch: python
  entry_points:
    - pdfstream = pdfstream.main:main
    - run_server = pdfstream.main:run_server
    - print_server_config_dir = pdfstream.main:print_server_config_dir
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - bluesky
    - databroker
    - fire
    - numba
    - pyfai
    - scikit-beam
    - suitcase-csv
    - suitcase-json-metadata
    - suitcase-tiff
    - xpdview
    - xray-vision

test:
  imports:
    - pdfstream
    - pdfstream.integration
    - pdfstream.transformation
    - pdfstream.utils
    - pdfstream.vend
    - pdfstream.visualization
  commands:
    - pdfstream -- --help

about:
  home: https://github.com/xpdAcq/pdfstream
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: The data analysis toolbox for the study on pair distribution function (PDF).

extra:
  recipe-maintainers:
    - mrakitin
    - kbeeperez
    - conda-forge/event-model
